// <auto-generated />
using FinalFantasy.RepositoryEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalFantasy.RepositoryEF.Migrations
{
    [DbContext(typeof(ContextFinalFantasy))]
    [Migration("20210709100626_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalFantasy.Core.Entities.Hero", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExperiencePoint")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("LifePoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeH")
                        .HasColumnType("int");

                    b.Property<int>("TypeM")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.HasIndex("WeaponID");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Monster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("LifePoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeH")
                        .HasColumnType("int");

                    b.Property<int>("TypeM")
                        .HasColumnType("int");

                    b.Property<int>("WeaponID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WeaponID");

                    b.ToTable("Most");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Level = 1,
                            LifePoints = 0,
                            Name = "Lucifer XX",
                            TypeH = 0,
                            TypeM = 1,
                            WeaponID = 0
                        });
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Giocatori");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Weapon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Class = "Hero",
                            Damage = 8,
                            Name = "Ascia"
                        },
                        new
                        {
                            ID = 2,
                            Class = "Hero",
                            Damage = 5,
                            Name = "Spada"
                        },
                        new
                        {
                            ID = 3,
                            Class = "Hero",
                            Damage = 10,
                            Name = "Mazza"
                        },
                        new
                        {
                            ID = 4,
                            Class = "Monster",
                            Damage = 7,
                            Name = "Arco"
                        },
                        new
                        {
                            ID = 5,
                            Class = "Monster",
                            Damage = 5,
                            Name = "Clava"
                        });
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Hero", b =>
                {
                    b.HasOne("FinalFantasy.Core.Entities.User", "User")
                        .WithMany("Heroes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalFantasy.Core.Entities.Weapon", "Weapon")
                        .WithMany("Heroes")
                        .HasForeignKey("WeaponID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Monster", b =>
                {
                    b.HasOne("FinalFantasy.Core.Entities.Weapon", "Weapon")
                        .WithMany("Monsters")
                        .HasForeignKey("WeaponID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.User", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Weapon", b =>
                {
                    b.Navigation("Heroes");

                    b.Navigation("Monsters");
                });
#pragma warning restore 612, 618
        }
    }
}
